# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

kernel:
  image: uos/kernel
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c
  - linuxkit/runc:v0.8
  - linuxkit/containerd:1ae8f054e9fe792d1dbdb9a65f1b5e14491cb106
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
  - uos/firmware-wifi:v1.0
onboot:
  - name: modprobe
    image: linuxkit/modprobe:v0.8
    command: ["modprobe", "-a", "virtio_net", "virtio_blk", "nvme-core", "mmc_block"]
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: sysfs
    image: linuxkit/sysfs:v0.8
  - name: rngd1
    image: linuxkit/rngd:v0.8
    command: ["/sbin/rngd", "-1"]
services:
  - name: wlan
    image: uos/wlan:v1.0
    capabilities:
      - all
    net: host
    binds:
      - /dev:/dev
      - /lib/firmware:/lib/firmware
      - /lib/modules:/lib/modules
      - /proc:/proc
      - /sys:/sys
      - /run/resolvconf/resolv.conf:/etc/system-resolv.conf
      - /var/services/wlan:/etc
    runtime:
        mkdir: ["/var/services/wlan"]
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
    binds.add:
      - /:/hostroot
      - /etc/issue:/etc/motd
      - /etc/getty.shadow:/etc/shadow
      - /etc/sshd.passwd:/etc/passwd
      - /etc/sshd.group:/etc/group
      - /etc/profile.d:/etc/profile.d
      - /usr/local/bin/uos:/usr/local/bin/uos
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
  - name: ntpd
    image: linuxkit/openntpd:v0.8
  - name: sshd
    image: linuxkit/sshd:v0.8
    binds.add:
      - /:/hostroot
      - /etc/issue:/etc/motd
      - /etc/getty.shadow:/etc/shadow
      - /etc/sshd.passwd:/etc/passwd
      - /etc/sshd.group:/etc/group
      - /etc/profile.d:/etc/profile.d
      - /etc/ssh/sshd_config:/etc/ssh/sshd_config
      - /home:/home
      - /lib/modules:/lib/modules
      - /usr/local/bin/uos:/usr/local/bin/uos
  - name: dyninit
    image: uos/dyninit:v1.0
    capabilities:
     - all
    pid: host
    net: host
    mounts:
      - type: cgroup
        options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
      - /:/hostroot
      - /dev:/dev
      - /etc/docker/daemon.json:/etc/docker/daemon.json
      - /etc/profile.d/profile.sh:/etc/profile.d/profile.sh
      - /lib/modules:/lib/modules
      - /root/.bashrc:/root/.bashrc
      - /run/resolvconf/resolv.conf:/etc/resolv.conf
      - /sys:/sys
      - /tmp:/tmp
files:
  - path: var/lib/docker
    directory: true
  - path: etc/ssh/sshd_config
    contents: |
      PasswordAuthentication yes
      PermitRootLogin yes
  - path: root/.ssh/authorized_keys
    contents: ""
      # ssh-rsa fill-this-in-with-an-ssh-key-if-you-want
    mode: "0600"
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
  - path: usr/local/bin/uos
    contents: |
      hostname uos
      ctr -n services.linuxkit t exec -t --exec-id dyninit-cli-$(uuidgen) dyninit bash
    mode: "0777"
  - path: root/.bashrc
    contents: |
      source /etc/profile
  - path: home/uos/.bashrc
    contents: |
      source /etc/profile
    uid: 1000
    gid: 1000
  - path: home/uos
    directory: true
    uid: 1000
    gid: 1000
  - path: etc/issue
    contents: |+
      
      .           /######   /######
                 /##__  ## /##__  ##
       /##   /##| ##  \ ##| ##  \__/
      | ##  | ##| ##  | ##|  ######
      | ##  | ##| ##  | ## \____  ##
      | ##  | ##| ##  | ## /##  \ ##
      |  ######/|  ######/|  ######/
       \______/  \______/  \______/
      
      
        Welcome to uOS.
      
  - path: etc/profile.d/aliases.sh
    contents: |
      alias docker="ctr -n services.linuxkit t exec -t --exec-id docker-cli-$(uuidgen) dyninit docker"
    mode: "0777"
  - path: etc/profile.d/profile.sh
    contents: |
      export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]# "
      if [ -f /usr/local/bin/uos ]; then /usr/local/bin/uos; fi
      cd ~
      if [ -f /opt/bootstrap/wifi-scan ]; then /opt/bootstrap/wifi-scan; fi
      export TERM=xterm
      resize
    mode: "0777"
  - path: etc/getty.shadow
    contents: |
      root:$6$CynZq8uqcMQH.Cbv$C.yZr/U9JMM0p/XmJGz2F1B6QLuYLqwhwz88b5CEc.GVH8XCKMMOULnjGyK7ro1olvsKS.c48B.mLwDw5iG9v0::0:::::
      bin:!::0:::::
      daemon:!::0:::::
      adm:!::0:::::
      lp:!::0:::::
      sync:!::0:::::
      shutdown:!::0:::::
      halt:!::0:::::
      mail:!::0:::::
      news:!::0:::::
      uucp:!::0:::::
      operator:!::0:::::
      man:!::0:::::
      postmaster:!::0:::::
      cron:!::0:::::
      ftp:!::0:::::
      sshd:!::0:::::
      at:!::0:::::
      squid:!::0:::::
      xfs:!::0:::::
      games:!::0:::::
      cyrus:!::0:::::
      vpopmail:!::0:::::
      ntp:!::0:::::
      smmsp:!::0:::::
      guest:!::0:::::
      nobody:!::0:::::
      uos:$6$1QMjH.ST8$2IDA3U50M925KDJwmtlC9e9g.8g2ZQYtiFi6.BXLFM11mXDvrFyFzl3GS6GOC7r3g5tTCOIVO1oN/tJQDpdX8/::0:::::
    mode: "644"
  - path: etc/sshd.passwd
    contents: |
      root:x:0:0:root:/root:/bin/ash
      bin:x:1:1:bin:/bin:/sbin/nologin
      daemon:x:2:2:daemon:/sbin:/sbin/nologin
      adm:x:3:4:adm:/var/adm:/sbin/nologin
      lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
      sync:x:5:0:sync:/sbin:/bin/sync
      shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
      halt:x:7:0:halt:/sbin:/sbin/halt
      mail:x:8:12:mail:/var/mail:/sbin/nologin
      news:x:9:13:news:/usr/lib/news:/sbin/nologin
      uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
      operator:x:11:0:operator:/root:/sbin/nologin
      man:x:13:15:man:/usr/man:/sbin/nologin
      postmaster:x:14:12:postmaster:/var/mail:/sbin/nologin
      cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
      ftp:x:21:21::/var/lib/ftp:/sbin/nologin
      sshd:x:22:22:sshd:/dev/null:/sbin/nologin
      at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
      squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
      xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
      games:x:35:35:games:/usr/games:/sbin/nologin
      cyrus:x:85:12::/usr/cyrus:/sbin/nologin
      vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
      ntp:x:123:123:NTP:/var/empty:/sbin/nologin
      smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
      guest:x:405:100:guest:/dev/null:/sbin/nologin
      nobody:x:65534:65534:nobody:/:/sbin/nologin
      uos:x:1000:1000:uos:/home/uos:/bin/ash
    mode: "644"
  - path: etc/sshd.group
    contents: |
      root:x:0:root,uos
      bin:x:1:root,bin,daemon
      daemon:x:2:root,bin,daemon
      sys:x:3:root,bin,adm
      adm:x:4:root,adm,daemon
      tty:x:5:
      disk:x:6:root,adm
      lp:x:7:lp
      mem:x:8:
      kmem:x:9:
      wheel:x:10:root
      floppy:x:11:root
      mail:x:12:mail
      news:x:13:news
      uucp:x:14:uucp
      man:x:15:man
      cron:x:16:cron
      console:x:17:
      audio:x:18:
      cdrom:x:19:
      dialout:x:20:root
      ftp:x:21:
      sshd:x:22:
      input:x:23:
      at:x:25:at
      tape:x:26:root
      video:x:27:root
      netdev:x:28:
      readproc:x:30:
      squid:x:31:squid
      xfs:x:33:xfs
      kvm:x:34:kvm
      games:x:35:
      shadow:x:42:
      cdrw:x:80:
      usb:x:85:
      vpopmail:x:89:
      users:x:100:games
      ntp:x:123:
      nofiles:x:200:
      smmsp:x:209:smmsp
      locate:x:245:
      abuild:x:300:
      utmp:x:406:
      ping:x:999:
      nogroup:x:65533:
      nobody:x:65534:
      uos:x:1000:
    mode: "644"
